#!/usr/bin/python
import sys


def cal_matrix_power(matrix: list, n: int):
    if n == 1:
        return matrix

    def multiply(matrix1: list, matrix2: list):
        n = len(matrix1)
        m = len(matrix1[0])
        p = len(matrix2[0])
        matrix = [[0 for _ in range(p)] for _ in range(n)]
        for i in range(n):
            for j in range(p):
                for k in range(m):
                    matrix[i][j] += matrix1[i][k] * matrix2[k][j]
        return matrix
    v = cal_matrix_power(matrix, n//2)
    if n % 2 == 0:
        return multiply(v, v)
    else:
        return multiply(matrix, multiply(v, v))


def cal_fb(n: int):
    matrix = [
        [1, 1],
        [1, 0]
    ]
    return cal_matrix_power(matrix, n)[0][0]


print(cal_fb(int(sys.argv[1])))
